# This file is generated
# Do not edit !!!
require_relative 'base'

module Onix
  module V3_0
    class DescriptiveDetail < Base
      node_attribute_accessor :datestamp, of_type: 'dt.DateOrDateTime'
      node_attribute_accessor :sourcetype, of_type: 'SourceTypeCode'
      node_attribute_accessor :sourcename, of_type: 'string'

      subnode_accessor :product_composition, for_tag: 'ProductComposition', min_occurs: '1', max_occurs: '1'
      subnode_accessor :product_form, for_tag: 'ProductForm', min_occurs: '1', max_occurs: '1'
      subnode_accessor :product_form_details, for_tag: 'ProductFormDetail', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :product_form_features, for_tag: 'ProductFormFeature', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :product_packaging, for_tag: 'ProductPackaging', min_occurs: '0', max_occurs: '1'
      subnode_accessor :product_form_descriptions, for_tag: 'ProductFormDescription', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :trade_category, for_tag: 'TradeCategory', min_occurs: '0', max_occurs: '1'
      subnode_accessor :primary_content_type, for_tag: 'PrimaryContentType', min_occurs: '0', max_occurs: '1'
      subnode_accessor :product_content_types, for_tag: 'ProductContentType', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :measures, for_tag: 'Measure', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :country_of_manufacture, for_tag: 'CountryOfManufacture', min_occurs: '0', max_occurs: '1'
      subnode_accessor :epub_technical_protections, for_tag: 'EpubTechnicalProtection', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :epub_usage_constraints, for_tag: 'EpubUsageConstraint', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :epub_license, for_tag: 'EpubLicense', min_occurs: '0', max_occurs: '1'
      subnode_accessor :map_scales, for_tag: 'MapScale', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :product_classifications, for_tag: 'ProductClassification', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :product_parts, for_tag: 'ProductPart', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :collections, for_tag: 'Collection', min_occurs: '1', max_occurs: 'unbounded'
      subnode_accessor :no_collection, for_tag: 'NoCollection', min_occurs: '1', max_occurs: '1'
      subnode_accessor :title_details, for_tag: 'TitleDetail', min_occurs: '1', max_occurs: 'unbounded'
      subnode_accessor :thesis_type, for_tag: 'ThesisType', min_occurs: '1', max_occurs: '1'
      subnode_accessor :thesis_presented_to, for_tag: 'ThesisPresentedTo', min_occurs: '0', max_occurs: '1'
      subnode_accessor :thesis_year, for_tag: 'ThesisYear', min_occurs: '0', max_occurs: '1'
      subnode_accessor :contributors, for_tag: 'Contributor', min_occurs: '1', max_occurs: 'unbounded'
      subnode_accessor :contributor_statements, for_tag: 'ContributorStatement', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :no_contributor, for_tag: 'NoContributor', min_occurs: '0', max_occurs: '1'
      subnode_accessor :events, for_tag: 'Event', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :conferences, for_tag: 'Conference', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :edition_types, for_tag: 'EditionType', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :edition_number, for_tag: 'EditionNumber', min_occurs: '1', max_occurs: '1'
      subnode_accessor :edition_version_number, for_tag: 'EditionVersionNumber', min_occurs: '0', max_occurs: '1'
      subnode_accessor :edition_statements, for_tag: 'EditionStatement', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :no_edition, for_tag: 'NoEdition', min_occurs: '0', max_occurs: '1'
      subnode_accessor :religious_text, for_tag: 'ReligiousText', min_occurs: '0', max_occurs: '1'
      subnode_accessor :languages, for_tag: 'Language', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :extents, for_tag: 'Extent', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :illustrated, for_tag: 'Illustrated', min_occurs: '0', max_occurs: '1'
      subnode_accessor :number_of_illustrations, for_tag: 'NumberOfIllustrations', min_occurs: '0', max_occurs: '1'
      subnode_accessor :illustrations_notes, for_tag: 'IllustrationsNote', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :ancillary_contents, for_tag: 'AncillaryContent', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :subjects, for_tag: 'Subject', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :name_as_subjects, for_tag: 'NameAsSubject', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :audience_codes, for_tag: 'AudienceCode', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :audiences, for_tag: 'Audience', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :audience_ranges, for_tag: 'AudienceRange', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :audience_descriptions, for_tag: 'AudienceDescription', min_occurs: '0', max_occurs: 'unbounded'
      subnode_accessor :complexities, for_tag: 'Complexity', min_occurs: '0', max_occurs: 'unbounded'
    end
  end
end
